# Generated by Django 4.1.3 on 2022-12-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=200)),
                ('items', models.TextField()),
                ('total_price', models.FloatField()),
                ('tax_price', models.FloatField()),
                ('purchase_date', models.DateField()),
                ('purchase_time', models.TimeField()),
                ('receipt_id', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
