# Generated by Django 4.1.3 on 2022-12-07 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='purchase_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
