# Generated by Django 4.1.3 on 2022-12-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0003_alter_receipt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_org',
            field=models.TextField(blank=True, null=True),
        ),
    ]
