# Generated by Django 4.1.3 on 2023-01-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0006_alter_receipt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
