version: '3.9'


services:
  # db:
  #   image: postgres:14-alpine
  #   ports:
  #     - '5432:5432'

  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=postgres

  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: frontend

    ports:
      - '5173:5173'

    volumes:
      - ./frontend:/frontend

    depends_on:
      - backend

  backend: 
    build: 
      context: .
      dockerfile: Dockerfile

    container_name: api

    # environment:
    #   - POSTGRES_PASSWORD=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_DB=postgres

    ports:
      - '8000:8000'

    volumes:
      - .:/api

    # depends_on:
    #   - db